name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Authenticate to GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
          <settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.GH_TOKEN }}</password>
              </server>
            </servers>
          </settings>" > $HOME/.m2/settings.xml

#      - name: Debug Maven settings
#        if: ${{ github.event_name == 'push' }}
#        run: cat $HOME/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        working-directory: ./kcp

      - name: Build and Publish Package
        run: mvn deploy
        working-directory: ./kcp

      - name: Update dependency graph
        run: |
          cd ./kcp
          mvn -B com.github.ferstl:depgraph-maven-plugin:4.0.1:graph
